language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - build-tools-23.0.3
    - android-24
    - android 23
    - extra-google-m2repository
    - extra-android-m2repository
cache:
    directories:
        - node_modules
env:
  - NODE_VERSION="4.4.7"
install:
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - npm install -g ionic cordova gulp
    - npm install
    - export PATH=$(npm bin):$PATH
    - bower install
    - gulp
    - chmod +x hooks/after_prepare/010_add_platform_class.js
script:
    - ionic platform add android
    - ionic resources
    - ionic build android
after_success:
  - chmod +x scripts/update-apk.sh
  - sh scripts/update-apk.sh
