language: android
sudo: false
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - android-25
    - build-tools-25.0.2
    - platform-tools
    - extra-google-m2repository
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
      - "${TRAVIS_BUILD_DIR}/gradle/caches/"
      - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
script:
  - ./gradlew build
  - ./gradlew testDebugUnitTestCoverage
after_failure:
  # tests
  - cat app/build/reports/tests/testDebugUnitTest/index.html

  # app
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - bash scripts/update-apk.sh
